### ISSUE TITLE
Build on Linux feedback

### ISSUE THREAD

**Issue by DerPit** [rlancaste/INDIWebManagerApp#1]
I just tried building it on my openSUSE Tumbleweed system.

Only some feedback, hoping it might help to improve things:

Cloned the repo, created a subdirectory 'build' and ran 'cmake ../' in there.
The compile would fail trying to resolve -lKF5::Auth in the link stage.  Checking the verbose make output I saw that for all other libs explicit paths were used, e.g., /usr/lib64/libKF5I18n.so.5.58.0.
Manually compiling with /usr/lib64/libKF5Auth.so.5.58.0 instead of -lKF5::Auth worked fine.
No idea though how to fix that in the cmake file....

Running it from the command line shows some error regarding an icon:
qt.svg: Cannot open file ':/media/images/configure.svg', because: No such file or directory
make install had only installed bin/INDIWebManagerApp and share/config.kcfg/INDIWebManagerApp.kcfg.

Terminating the application with the X-button leads to a segmentation fault.

**Comment by rlancaste** [comment]
found the issue, it was a typo, it should be ":/media/icons/configure.svg"

**Comment by rlancaste** [comment]
I think I might have found something in the shutdown procedure that could sometimes cause a null pointer exception.  I fixed that.

**Comment by rlancaste** [comment]
I'm confused about KAuth, because I don't use that.

**Comment by rlancaste** [comment]
Please test again to see if your issues are resolved

**Comment by DerPit** [comment]
The svg error is gone :)
KAuth likely is pulled in via some dependency?  I just noticed a warning when running cmake (I had used -Wno-dev last time):
  Target "INDIWebManagerApp" links to target "KF5::Auth" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
If I add Auth to the find_package call for KF5 in CMakeLists.txt it doesn't complain anymore and compiles fine.
The SIGSEGV is still there on exit.  I first thought it might be related to a missing indi-web, but that is now installed, too, and it still crashes :(  I had a quick try using gdb, but the BT only listed QT stuff?
[gdb.out.gz](https://github.com/rlancaste/INDIWebManagerApp/files/3313749/gdb.out.gz)
I'll see if I can get further there.

I can now use it to start indi-web, but clicking on 'Open WebManager' directs my browser to the URL http://localhost/?line=8624&column=0 instead of http://localhost/:8624 (Browser is chromium-based Vivaldi)

**Comment by rlancaste** [comment]
Hmm. . In the button to open the web manager, I just tell it to open  "http://localhost:8624". I tested this on both ubuntu and OS X.  It seems to work.  I'm not sure I understand why on your system it would open "http://localhost/?line=8624&column=0"

**Comment by DerPit** [comment]
rlancasteAstro wrote:
> Hmm. . In the button to open the web manager, I just tell it to open  "http://localhost:8624". I tested this on both ubuntu and OS X.  It seems to work.  I'm not sure I understand why on your system it would open "http://localhost/?line=8624&column=0"
> 

Hmm.  It indeed happens also if I use the standard 'xdg-open
http://localhost:8624' (not only that URL, but any that includes a port).

First thought it's vivaldi, but if I instead do a 'vivaldi
http://localhost:8624' it does open that properly in the running instance.
Not sure what is going on there.  I'll try to find out...

**Comment by rlancaste** [comment]
I just tried on ubuntu using firefox and then chromium.  For both it currently opens correctly.  If you can find out the issue, please let me know.

**Comment by DerPit** [comment]
rlancasteAstro wrote:
> I just tried on ubuntu using firefox and then chromium.  For both it currently opens correctly.  If you can find out the issue, please let me know.
> 

I think it's a bug in kde-open5 (that is what xdg-open uses in the end, and
most likely also the Qt code).  At least I get the same problem when I use it
directly, both on my laptop (with vivaldi) and on another machine/user with
firefox.  If I use 'gio open <URL>' (gnome way) it works as expected.

This is Tumbleweed, running KDE/KF5/Plasma 5.16.0.  So either a new thing - or
on your machine a different backend is used?

I've opened a bugreport for it:
https://bugzilla.opensuse.org/show_bug.cgi?id=1138956

**Comment by rlancaste** [comment]
Is this a similar issue to yours perhaps?

https://github.com/texstudio-org/texstudio/issues/28

**Comment by DerPit** [comment]
rlancasteAstro wrote:
> Is this a similar issue to yours perhaps?
> 
> https://github.com/texstudio-org/texstudio/issues/28

Not really, except that the calling program is innocent :)
You are also just using the officially recommended way to access/open
something, and that then causes some trouble.

In my case, as expected, it was/is an error introduced in the latest KDE
version.  It should get fixed upstream soon.

**Comment by rlancaste** [comment]
Any idea if this has been resolved?

**Comment by DerPit** [comment]
Unfortunately, no.  I'm at 5.16.2 now, and it still does that crap.

Not sure how many distributions are actually affected by that, many are probably still at 5.15 (or lower?), or use GNOME...

**Comment by DerPit** [comment]
Sorry, wanted to report back earlier...
It had been fixed in my Distribution with a temporary patch a week ago or so, meanwhile 5.16.4 is out that has fixed the issue upstream.

**Comment by rlancaste** [comment]
That is good news!
