### ISSUE TITLE
message pop up everytime INDIWebManagerAPP startup

### ISSUE THREAD

**Issue by tlkw79** [rlancaste/INDIWebManagerApp#2]
Hi,

I always encounter this message during indiwebmanagerapp startup "Alert, an INDI Webmanager is already running on this computer. Do you want to quit it?" 

Any idea how to stop the other indi webmanager from starting up during OS startup?

Thanks

**Comment by rlancaste** [comment]
I am assuming this is on a Linux computer like a raspberry pi?  Do you have an INDI Web Manager set to auto start such as indiwebmanager.service as described on this website? https://github.com/knro/indiwebmanager

Or maybe do you have something in  /etc/init.d that starts it?
